inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 200
  Exclude:
    - 'spec/support/stub_aspace_client.rb'
    - 'spec/support/stub_aspace.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/peoplesoft_voucher/alma_xml_invoice.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'lib/tasks/lib_jobs.rake'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/staff_directory_generator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/ability.rb'
    - 'app/models/web_staff/ldap.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/application_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/ability.rb'
    - 'app/models/web_staff/ldap.rb'

RSpec/ExampleLength:
  Max: 100

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
