---
version: 2.1
executors:
  lib-jobs-executor:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          lando_libjobs_database_creds_user: "libjobs"
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: libjobs
          POSTGRES_DB: libjobs_test
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/project

commands:
  setup-bundler:
    description: "Install correct version of bundler and load from cache or bundle install"
    steps:
      - run: sudo apt-get  --allow-releaseinfo-change update
      - run: sudo apt-get install cifs-utils unixodbc unixodbc-dev freetds-dev freetds-bin tdsodbc
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - lib-jobs-bundle-v3-{{ checksum "Gemfile.lock" }}
            - lib-jobs-bundle-v3-
  setup-node:
    description: "Install the correct release of NodeJS and install the JavaScript package dependencies"
    steps:
      - run:
          name: Install node@lts/erbium (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install lts/erbium' >> $BASH_ENV
            echo 'nvm alias default lts/erbium' >> $BASH_ENV
      - run:
          name: Check current version of NodeJS
          command: node -v
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - lib-jobs-node-{{ checksum "yarn.lock" }}
      - run:
          name: Install the NPM package dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: lib-jobs-node-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: lib-jobs-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  build:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - checkout
      - setup-bundler
      - setup-node
      - persist_to_workspace:
          root: '~/project'
          paths: '*'

  test:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - setup-node
      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:migrate

      # Run rspec with percy
      - run:
          name: Run rspec
          command: |
            bundle list
            bundle exec rspec

      # Save coverage artifacts
      - store_artifacts:
          path: ~/project/coverage
          destination: coverage

      # Save screenshot artifacts
      - store_artifacts:
          path: ~/project/tmp/screenshots
          destination: screenshots

      - persist_to_workspace:
          root: '~/project'
          paths: '*'

  rubocop:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: bundle exec rubocop

  prettier-eslint:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: yarn run lint

  jest:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: yarn run jest
      - persist_to_workspace:
          root: '~/project'
          paths: '*'

workflows:
  build_accept:
    jobs:
      - build
      - rubocop:
         requires:
          - build
      - prettier-eslint:
         requires:
          - build
      - test:
         requires:
          - build
      - jest:
         requires:
          - build
