---
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
  node: circleci/node@5.1.0
executors:
  lib-jobs-executor:
    docker:
      - image: cimg/ruby:3.1.2-browsers
        environment:
          BUNDLER_VERSION: 2.3.11
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          lando_libjobs_database_creds_user: "libjobs"
      - image: postgres:13.10-alpine
        environment:
          POSTGRES_USER: libjobs
          POSTGRES_DB: libjobs_test
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/project

commands:
  setup-bundler:
    description: "Install correct version of bundler and load from cache or bundle install"
    steps:
      - run: sudo apt-get --allow-releaseinfo-change update
      - run: sudo apt-get install cifs-utils unixodbc unixodbc-dev freetds-dev freetds-bin tdsodbc
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - lib-jobs-bundle-v3-{{ checksum "Gemfile.lock" }}
            - lib-jobs-bundle-v3-
  setup-node:
    description: "Install the correct release of NodeJS and install the JavaScript package dependencies"
    steps:
      - node/install:
          install-yarn: true
          node-version: '16.19.0'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - lib-jobs-node-{{ checksum "yarn.lock" }}
      - run:
          name: Install the NPM package dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: lib-jobs-node-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: lib-jobs-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  build:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - checkout
      - setup-bundler
      - setup-node
      - persist_to_workspace:
          root: '~/project'
          paths: '*'

  test:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - setup-node
      - browser-tools/install-browser-tools
      - run:
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
            java -jar /usr/local/bin/selenium.jar --version
          name: Check install
      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:migrate

      # Run rspec with percy
      - run:
          name: Run rspec
          command: |
            bundle list
            bundle exec rspec

      # Save coverage artifacts
      - store_artifacts:
          path: ~/project/coverage
          destination: coverage

      # Save screenshot artifacts
      - store_artifacts:
          path: ~/project/tmp/screenshots
          destination: screenshots

      - persist_to_workspace:
          root: '~/project'
          paths: '*'

  rubocop:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: bundle exec rubocop

  brakeman:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: bundle exec brakeman

  prettier-eslint:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: yarn run lint

  jest:
    executor: lib-jobs-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: yarn run jest
      - persist_to_workspace:
          root: '~/project'
          paths: '*'

workflows:
  build_accept:
    jobs:
      - build
      - rubocop:
         requires:
          - build
      - brakeman:
         requires:
          - build
      - prettier-eslint:
         requires:
          - build
      - test:
         requires:
          - build
      - jest:
         requires:
          - build
