default: &default
  host: <%= ENV['SFTP_HOST'] || 'localhost2' %>
  username: <%= ENV['SFTP_USERNAME'] || 'alma' %>
  password: <%= ENV['SFTP_PASSWORD'] || 'change_me' %>
  voucher_feed_path: <%= ENV["VOUCHER_FEED_INPUT_FTP"] || '/alma/invoices' %>
  person_feed_path: <%= ENV["ALMA_PERSON_FEED_OUTPUT_FTP"] || '/alma/people' %>
  fund_adjustment_path: <%= ENV["ALMA_FUND_ADJUSTMENT_OUTPUT_FTP"] || '/alma/fund_adjustment' %>
  invoice_status_path: <%= ENV["ALMA_INVOICE_STATUS_OUTPUT_FTP"] || '/alma/invoice_status' %>
  invoice_status_local_path: <%= ENV["ALMA_INVOICE_STATUS_LOCAL_DIR"] || '/tmp' %>
  pod_output_path: <%= ENV["ALMA_POD_OUTPUT_DIR"] || '/alma/pod' %>
  renew_report_path: <%= ENV["ALMA_RENEW_INPUT_DIR"] || '/alma/scsb_renewals' %>
  bursar_report_path: <%= ENV["ALMA_BURSAR_INPUT_DIR"] || '/alma/bursar' %>
  alma_recap_output_path: <%= ENV["ALMA_RECAP_OUTPUT_DIR"] || '/alma/recap' %>

development:
  <<: *default

test:
  <<: *default
  invoice_status_local_path: 'spec/fixtures/ephemeral'
staging: &staging
  <<: *default

production:
  <<: *staging
