default: &default
  local_svn_dir: subversion_eads
  svn_username: <%= ENV["SVN_USERNAME"] || 'libjobs' %>
  svn_password: <%= ENV["SVN_PASSWORD"] %>
  svn_host: <%= ENV["SVN_HOST"] %>
  git_lab_host: <%= ENV["GIT_LAB_HOST"] || 'gitlab-prod-vm.lib.princeton.edu' %>
  git_lab_source_path: scua/eads
  local_git_lab_dir: git_lab_eads
  git_lab_local_repo_path: git_lab_eads
  repos: 
    3: "mudd/publicpolicy"
    4: "mudd/univarchives"
    5: "mss"
    6: "rarebooks"
    7: "cotsen"
    8: "lae"
    9: "eng"
    10: "selectors"
    11: "ga"
    12: "ea"

development:
  <<: *default
  repos: 
    12: "ea"
  git_lab_host: <%= ENV["GIT_LAB_HOST"] || 'gitlab-staging-vm.lib.princeton.edu' %>
  local_git_lab_dir: tmp/gitlab_eads
  git_lab_local_repo_path: tmp/gitlab_eads

test:
  <<: *default
  local_svn_dir: tmp/subversion_eads
  svn_username: "test-username"
  svn_password: "test-password"
  svn_host: "pretend-svn-host1.princeton.edu"
  git_lab_host: 'gitlab-staging-vm.lib.princeton.edu'
  git_lab_source_path: mk8066/test-project-for-cloning
  local_git_lab_dir: tmp/gitlab_eads
  git_lab_local_repo_path: tmp/gitlab_eads
  repos: 
    3: "mudd/publicpolicy"
    6: "rarebooks"
    11: "ga"
    12: "ea"

staging:
  <<: *default
  git_lab_host: <%= ENV["GIT_LAB_HOST"] || 'gitlab-staging-vm.lib.princeton.edu' %>
  repos: 
    10: "selectors"
    11: "ga"

production:
  <<: *default
