default: &default
  aspace_files_output_path: subversion_eads
  svn_username: <%= ENV["SVN_USERNAME"] || 'libjobs' %>
  svn_password: <%= ENV["SVN_PASSWORD"] %>
  svn_host: <%= ENV["SVN_HOST"] %>
  repos: 
    3: "mudd/publicpolicy"
    4: "mudd/univarchives"
    5: "mss"
    6: "rarebooks"
    7: "cotsen"
    8: "lae"
    9: "eng"
    10: "selectors"
    11: "ga"
    12: "ea"

development:
  <<: *default
  repos: 
    12: "ea"

test:
  <<: *default
  aspace_files_output_path: tmp/subversion_eads
  svn_username: "test-username"
  svn_password: "test-password"
  svn_host: "pretend-svn-host1.princeton.edu"

staging:
  <<: *default

production:
  <<: *default
