default: &default
  aspace_files_output_path: <%= 'subversion_eads' %>

development:
  <<: *default

test:
  <<: *default
  aspace_files_output_path: tmp

staging:
  <<: *default

production:
  <<: *default
