default: &default
  local_svn_dir: subversion_eads
  svn_username: <%= ENV["SVN_USERNAME"] || 'libjobs' %>
  svn_password: <%= ENV["SVN_PASSWORD"] %>
  svn_host: <%= ENV["SVN_HOST"] %>
  git_lab_host: <%= ENV["GIT_LAB_HOST"] || 'gitlab-prod-vm.lib.princeton.edu' %>
  git_lab_source_path: scua/libsvn
  local_git_lab_dir: git_lab_eads
  local_git_lab_eacs_dir: git_lab_eacs
  git_lab_local_repo_path: git_lab_eads
  repos: 
    3: "eads/mudd/publicpolicy"
    4: "eads/mudd/univarchives"
    5: "eads/mss"
    6: "eads/rarebooks"
    7: "eads/cotsen"
    8: "eads/lae"
    9: "eads/eng"
    10: "eads/selectors"
    11: "eads/ga"
    12: "eads/ea"
  repo_eacs:
    1: "eacs"

development:
  <<: *default
  repos: 
    12: "libsvn/eads/ea"
  git_lab_host: <%= ENV["GIT_LAB_HOST"] || 'gitlab-staging-vm.lib.princeton.edu' %>
  local_git_lab_dir: tmp/gitlab_eads
  local_git_lab_eacs_dir: tmp/gitlab_eacs
  git_lab_local_repo_path: tmp/gitlab_eads

test:
  <<: *default
  git_lab_host: 'gitlab-staging-vm.lib.princeton.edu'
  git_lab_source_path: mk8066/test-project-for-cloning
  local_git_lab_dir: tmp/gitlab_eads
  local_git_lab_eacs_dir: tmp/gitlab_eacs
  git_lab_local_repo_path: tmp/gitlab_eads
  repos: 
    3: "eads/mudd/publicpolicy"
    6: "eads/rarebooks"
    11: "eads/ga"
    12: "eads/ea"

staging:
  <<: *default
  git_lab_host: <%= ENV["GIT_LAB_HOST"] || 'gitlab-staging-vm.lib.princeton.edu' %>
  repos: 
    10: "eads/selectors"
    11: "eads/ga"

production:
  <<: *default
