default: &default
  aspace_files_output_path: subversion_eads
  svn_username: <%= ENV["SVN_USERNAME"] || 'libjobs' %>
  svn_password: <%= ENV["SVN_PASSWORD"] %>
  svn_host: <%= ENV["SVN_HOST"] %>

development:
  <<: *default

test:
  <<: *default
  aspace_files_output_path: tmp/subversion_eads
  svn_username: "test-username"
  svn_password: "test-password"
  svn_host: "pretend-svn-host1.princeton.edu"

staging:
  <<: *default

production:
  <<: *default
