---
defaults: &defaults
  sizes:
    global:
      'Objects': 'C'
      'BoxQ': 'L'
      'Double Elephant size box': 'Z'
      'Double Elephant volume': 'D'
      'Elephant size box': 'P'
      'Elephant volume': 'E'
      'Folio': 'F'
      'NBox': 'B'
      'Ordinary': 'N'
      'Quarto': 'Q'
      'Small': 'S'
    mudd:
      'Mudd OS depth': 'DO'
      'Mudd OS height': 'H'
      'Mudd OS length': 'LO'
      'Mudd OS Extra height': 'XH'
      'Mudd OS Extra height, depth': 'XHD'
      'Mudd ST records center': 'S'
      'Mudd ST manuscript': 'S'
      'Mudd ST half-manuscript': 'S'
      'Mudd ST other': 'S'
      'Mudd OS open': 'O'
      'Mudd Oversize folder': 'C'

  repositories:
    classifiers:
      'ctsn': 'cotsen'
      'ex': 'rarebooks' # Firestone Library, Vault, Rare Books
      'hsvm': 'mss' # Firestone, High Security Vault, Manuscripts
      'mss': 'mss' # Firestone Library, Vault, Manuscripts
      'rcpxm': 'mss' # ReCAP, Manuscripts

  hmac_secret: <%= ENV["HMAC_SECRET"] || 'secret' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
