---
defaults: &defaults

  hmac_secret: <%= ENV["HMAC_SECRET"] || 'secret' %>

  voucher_feed_recipients: <%= ENV.fetch('VOUCHER_FEED_RECIPIENTS', 'test_user@princeton.edu').split(',') %>
  alma_people_error_notification_recipients: <%= ENV.fetch('PEOPLE_ERROR_NOTIFICATION_RECIPIENTS', 'test_user@princeton.edu').split(',') %>
  peoplesoft_bursar_recipients: <%= ENV.fetch('PEOPLESOFT_BURSAR_RECIPIENTS', 'test_user@princeton.edu').split(',') %>
  peoplesoft_bursar_no_report_recipients: <%= ENV.fetch('PEOPLESOFT_BURSAR_NO_REPORT_RECIPIENTS', 'test_user@princeton.edu').split(',') %>
  transaction_error_feed_recipients: <%= ENV.fetch('TRANSACTION_ERROR_FEED_RECIPIENTS', 'test_user@princeton.edu').split(',') %>

  ncip_renew_from_agency: "01PRI_INST"
  ncip_renew_to_agency: "01PRI_INST"
  ncip_renew_application_profile: "SCSB"
  ncip_renew_alma_url: "https://princeton.alma.exlibrisgroup.com/view/NCIPServlet"
  pod_default_stream: <%= ENV["POD_DEFAULT_STREAM"] || "princeton-prod-0223" %>
  pod_test_stream: <%= ENV["POD_TEST_STREAM"] || "princeton-test-set" %>

  libcal_cid: <%= ENV["LIBCAL_CID"] || "12260" %>
  libcal_k: <%= ENV["LIBCAL_K"] || "79a5e62a54" %>

  libguides_client_id: <%= ENV["LIBGUIDES_CLIENT_ID"] || "630" %>
  libguides_client_secret: <%= ENV["LIBGUIDES_CLIENT_SECRET"] %>

  open_marc_records_location: <%= ENV["OPEN_MARC_RECORDS_LOCATION"] || "./open_marc_records/" %>

development:
  <<: *defaults

test:
  <<: *defaults
  open_marc_records_location: "spec/fixtures/open_marc_records"

production: &production
  <<: *defaults
  
staging:
  <<: *production
