default: &default
  limited_locations:
    - arch$ref
    - arch$la
    - eastasian$cjkref
    - eastasian$ref
    - eastasian$hyref
    - engineer$ref
    - firestone$aas
    - firestone$dra
    - firestone$dr
    - firestone$drrr
    - firestone$flm
    - firestone$sc
    - firestone$se
    - firestone$slav
    - firestone$sh
    - firestone$shs
    - firestone$sne
    - firestone$spc
    - firestone$sss
    - firestone$ssa
    - firestone$srel
    - firestone$gestf
    - firestone$dss
    - firestone$fis
    - firestone$sps
    - firestone$seref
    - firestone$egsr
    - firestone$gss
    - firestone$noncirc
    - firestone$necnc
    - firestone$clasnc
    - firestone$xlnc
    - firestone$secw
    - firestone$ssrcfo
    - firestone$ssrcdc
    - plasma$ref
    - plasma$rr
    - plasma$la
    - plasma$li
    - plasma$theses
    - plasma$nb
    - lewis$lal
    - lewis$laf
    - lewis$refid
    - lewis$ref
    - marquand$fesrf
    - marquand$ph
    - marquand$phref
    - marquand$ref
    - mendel$rg
    - mendel$facs
    - mendel$ref
    - mendel$pe
    - mudd$scamudd
    - rare$gestrare
    - rare$scactsn
    - rare$scathx
    - rare$scahsvm
    - rare$scagax
    - rare$scaex
    - rare$scamss
    - rare$scawa
    - rare$scahsvc
    - rare$scawhs
    - stokes$ref
  shared_locations:
    - recap$pa
    - recap$gp
    - mendel$qk
    - firestone$pf
    - marquand$pv

development:
  <<: *default

test:
  <<: *default

staging: &staging
  <<: *default

production:
  <<: *staging
