default: &default
  pod_record_path: <%= ENV["POD_RECORD_DIR"] || '/tmp' %>
  days_to_fetch: 7

development:
  <<: *default

test:
  <<: *default

staging: &staging
  days_to_fetch: 1

production:
  <<: *staging