default: &default
  scsb_auth_key: <%= ENV["SCSB_AUTH_KEY"] || 'scsb-auth-key' %>
  scsb_server: <%= ENV["SCSB_SERVER"] || 'https://test.api.com/' %>
  scsb_s3_access_key: <%= ENV["SCSB_S3_ACCESS_KEY"] %>
  scsb_s3_secret_access_key: <%= ENV["SCSB_S3_SECRET_ACCESS_KEY"] %>
  scsb_s3_bucket_name: <%= ENV["SCSB_S3_BUCKET_NAME"] %>
  scsb_s3_partner_access_key: <%= ["SCSB_S3_PARTNER_ACCESS_KEY"] %>
  scsb_s3_partner_secret_access_key: <%= ENV["SCSB_S3_PARTNER_SECRET_ACCESS_KEY"] %>
  scsb_s3_partner_bucket_name: <%= ENV["SCSB_S3_PARTNER_BUCKET_NAME"] || 'scsb-prod' %>
  scsb_s3_partner_fulls: <%= ENV["SCSB_S3_PARTNER_FULLS"] || 'data-exports/PUL/MARCXml/Full' %>
  scsb_s3_partner_updates: <%= ENV["SCSB_S3_PARTNER_UPDATES"] || 'data-exports/PUL/MARCXml/Incremental' %>
  scsb_s3_partner_deletes: <%= ENV["SCSB_S3_PARTNER_DELETES"] || 'data-exports/PUL/Json' %>
  scsb_s3_updates: <%= ENV["SCSB_S3_UPDATES"] || 'data-feed/submitcollections/PUL/cgd_protection' %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
