default: &default
  scsb_auth_key: <%= ENV["SCSB_AUTH_KEY"] || 'scsb-auth-key' %>
  scsb_server: <%= ENV["SCSB_SERVER"] || 'https://test.api.com/' %>
  scsb_s3_bucket_name: <%= ENV["SCSB_S3_BUCKET_NAME"] || 'test' %>
  scsb_s3_partner_access_key: <%= ENV["SCSB_S3_PARTNER_ACCESS_KEY"] || '1234klm' %>
  scsb_s3_partner_secret_access_key: <%= ENV["SCSB_S3_PARTNER_SECRET_ACCESS_KEY"] || '1234abc' %>
  scsb_s3_updates: <%= ENV["SCSB_S3_UPDATES"] || 'data-feed/submitcollections/PUL/cgd_protection' %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
