production:
  report_directory: <%= ENV['STAFF_REPORT_DIRECTORY'] %>
staging:
  report_directory: <%= ENV['STAFF_REPORT_DIRECTORY'] %>
development:
  report_directory: <%= Rails.root.join('tmp') %>
test:
  report_directory: <%= Rails.root.join('tmp') %>
